const express=require("express")
const mongoose=require('mongoose')
const cors=require('cors')
const app=express()
const dbConnect=require('./Connection/index')
dbConnect()
app.use(cors())
app.use(express.json())
app.use('/auth/',require('./routes/user'))
app.use('/notes/',require('./routes/note'))
app.listen(4000,function(){
    console.log("Server is listening at 4000")
})