const express=require("express")
const mongoose=require('mongoose')
const cors=require('cors')
const app=express()
mongoose.connect('mongodb://127.0.0.1:27017/Notebook1')
app.use(cors())
app.use(express.json())
app.use('/auth/',require('./routes/user'))
app.use('/notes/',require('./routes/note'))
app.listen(4000,function(){
    console.log("Server is listening at 4000")
})